### ISSUE TITLE
Invalid credentials when using % sign in password

### ISSUE THREAD

**Issue by Pol2Tls** [cnico/flipr-api#3]
Hi @cnico,
Thank you for this great job !
Just one issue, it doesn't seem to work when using % (percent sign) in the password.
The only way to have it working was to change the password to one without the  % character.

**Comment by cnico** [comment]
Hi @Pol2Tls,

I tried to reproduce your problem with a % character in the password but was not able to reproduce it.
Actually, I changed my password with a % at the end or at the beginning and it worked successfully.

You can debug it by adding this line of code in session.py line 41 : 
print(response.request.body)

Do you confirm the bug in another situation ?

As is, I do not find anything to correct in the code.

**Comment by Pol2Tls** [comment]
Hi @cnico,
The error is:
{"error":"invalid_grant","error_description":"Wrong user name or password"}
FAILED tests/test_integrations.py::test_integration_simple - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://apis.goflipr.c...

But it works with iPhone application.
I can reproduce this with PASSWORD="bQsfF5nSOWqeYZ3PXk%Gus5&*"

**Comment by cnico** [comment]
En effet, ce n'est pas le % qui posait problème mais le "&".

J'ai fait la correction adéquate pour que tout caractère dans le login et le password puisse être pris en compte.

C'est la v1.4.0 qui contient la correction.
