### ISSUE TITLE
 Support de Flipr me demande de passer une commande curl

### ISSUE THREAD

**Issue by Percherie** [cnico/flipr-api#5]
Bonjour, je fait suite après la fermeture du ticket qui aurai du être rédigé en anglais sur https://github.com/home-assistant/core/issues/99420

Voici le contenu du message précédent. Le retour du support de Flipr fait suite à un ticket ouvert chez eux indiquant que leur API est régulièrement en erreur 502. La valeur retourné est donc "unavailable"

Bonjour,

Suite au retour que j'ai fait auprès du support de Flipr, ils me demande de passer une commande curl

Depuis debian je sais l'exécuter mais je ne sais pas quel paramètres passer.

Voici le contenu de la commande
curl --location 'https://apis.goflipr.com//modules/C16BE5/NewResume'
--header 'Authorization: bearer <YOUR BEARER/User Token>
--header 'Cookie: ...; ARRAffinitySameSite=...'

Sur ce point j'aurai besoin d'aide ou qu'une personne plus expérimenté prenne le relais.

En complément, pour tracer le moment où l'API est indisponible j'ai cet automatisme

`
alias: Flipr - Alerte API indisponible
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.spa_flipr_ph
    to: null
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: |
          {{ trigger.from_state.state == 'unavailable' }}
      - condition: template
        value_template: |
          {{ trigger.from_state.state == 'unknown' }}
      - condition: template
        value_template: |
          {{ trigger.to_state.state == 'unavailable' }}
      - condition: template
        value_template: |
          {{ trigger.to_state.state == 'unknown' }}
action:
  - service: notify.mobile_app_huawei
    data:
      message: >-
        API Flipr indisponible. Valeur {{ trigger.from_state.state }}, vérifiez
        l'application Flipr immédiatement
mode: single
`

**Comment by cnico** [comment]
Bonjour, 

Perso, j'utilise plutôt postman mais ça le fait très bien avec curl aussi.
Voici comment procéder avec curl : 
il faut faire une première requête d'authentification en mettant vos valeurs de login et mot de passe flipr : 
curl -v -d 'grant_type=password' -d 'username=[EMAIL]' --data-urlencode 'password=[PASS]' https://apis.goflipr.com/OAuth2/token

Dans la réponse en json, il y a un attribut access_token dont il faut passer la valeur pour la requête suivante : 
curl -v --location 'https://apis.goflipr.com/modules/[FLIPR_ID]/NewResume' --header 'Authorization: bearer [TOKEN]'

Le résultat en json est très peu lisible mais, ça marche : je viens de le tester avec mon flipr.

Voilà, ça devrait vous permettre de diagnostiquer plus finement au niveau connexion avec les serveurs goflipr ce qu'il se passe.

**Comment by Percherie** [comment]
Nickel je vais mettre en place ce qu'il faut pour lancer la requête quand l'API ne répond plus.

Pour un autre problème de connexion avec l'application Flipr, le service back-end à répondu que ça venait de l'usage trop fréquent de leur API et que mon IP était temporairement bloqué.

Quel est la fréquence d'interrogation de l'API ? Où puis-je modifier la fréquence de rafraîchissement ?
Entre HA et l'application Flipr qui lancent leurs requête chacun de leur côté, ça pourrait en effet black lister mon IP

**Comment by cnico** [comment]
Je ne pense pas que ce soit un problème d'usage excessif de l'API. Je ne l'ai jamais rencontré de mon côté.
Le polling de l'intégration flipr se fait en appelant l'API une fois par heure : c'est en dur dans le code et non modifiable.

Le seul cas potentiel auquel je pense, c'est si vous avez plusieurs serveurs homeassistant qui appelent l'intégration flipr en même temps. Hormis pour des phases de développement, je ne vois pas pourquoi il y aurait une telle situation.

**Comment by Percherie** [comment]
désolé pour le temps de réponse, je me suis focalisé sur l'automate effectuant les conseils de traitement.

L'infra côté Flipr été saturé dimanche 01/10/2023, j'ai remonté une erreur 500 au matin et même un dimanche leur service infra m'a laissé un msg sur répondeur.
Je surveille et probablement que ça sera résolu

En attendant j'ai un automate qui m'alertera en cas de valeur unknown ou unavailable.. reste à avoir un pc sous la main pour effectuer le curl ;-p

**Comment by cnico** [comment]
Sujet clos
