### ISSUE TITLE
Intégration en erreur 400

### ISSUE THREAD

**Issue by Percherie** [cnico/flipr-api#6]
Bonjour,

Je viens de redémarrer HA et depuis l'intégration me remonte une erreur 400. J'ai donc un problème de mon côté.

> Config entry '<mon_flipr>' for flipr integration not ready yet: 400 Client Error: Bad Request for url: https://apis.goflipr.com/OAuth2/token; Retrying in background 

Il semble que j'ai un problème d'authentification. Quel serait la meilleur façon de procéder ?

- Désactiver l'intégration quelques heures pour ne pas spammer leur serveur ? Et retenter après ?
- Supprimer l'intégration et refaire l'authentification ?

Au plaisir de te lire

**Comment by cnico** [comment]
Ca vient probablement d'un changement de mot de passe fait dans l'application goflipr et non répercuté dans l'intégration home assistant.
Dans ce cas, il faut tout simplement supprimer l'appareil flipr généré par l'intégration et le récréer avec le nouveau mot de passe.

**Comment by Percherie** [comment]
Ça à l'air d'être un reset de MdP imposé par Flipr. Je ne l'ai pas modifié depuis près de deux ans.

Je viens de me déconnecter de l'application et elle indique une erreur de MdP.  Le mot de passe stocké dans mon coffre ne correspond plus. La récupération de MdP ne renvoie pas de mail non plus.
Je remonte l'info chez eux, c'est probablement lié à la maintenance qu'ils ont fait samedi 30 septembre

**Comment by Percherie** [comment]
Fausse alerte, le sav avait modifié mon mot de passe le temps de résoudre leur erreur 500 et ils n'avait pas rétabli le token
