### ISSUE TITLE
Intégration en erreur et test API répond correctement

### ISSUE THREAD

**Issue by Percherie** [cnico/flipr-api#7]
Bonjour Nico, c'est Joël

Depuis ce matin j'ai l'intégration qui n'arrive plus à communiquer avec l'API. J'ai le message d'erreur "Echec de l'intégration, nouvel essai"
Je viens de tester avec Postman et j'arrive à remonter correctement les informations.

Par chance, je n'ai pas encore modifié l'identifiant et mot de passe pour le F35861F2.
Peut-tu vérifier ce qu'il se passe ?
J'ai redémarré plusieurs fois HA, désactivé et réactivé l'intégration plusieurs fois et testé les différentes combinaison de démarrage / état de l'intégration;

Ps : j'avance à grand pas sur la version 5 de l'automate Flipr. Je finalise la gestion des notifications et des logs. Je t'enverrai le tout quand ce sera finalisé

**Comment by Percherie** [comment]
J'ai cherché dans les log de HA et je ne sais pas quoi t'envoyer. Dans les log je ne vois d'information claire.
Que te faut-il comme information ?

En te remerciant par avance
Passe une bonne soirée
Joël

**Comment by cnico** [comment]
Salut Joel,
C'est pas un problème de l'intégration mais une limite mise en place par l'équipe de flipr pour bloquer temporairement les accès depuis les clients python comme la librairie flipr-api. 
Je t'invite à suivre ça via : https://github.com/home-assistant/core/issues/108955
Dans l'immédiat, j'ai fait quelques tests et j'ai le même problème que toi dans mon Homeassistant. Je vais attendre de voir ce qui se passe au niveau du rétablissement de l'API goflipr.
